@host=http://localhost:3000

### signup a user
POST {{host}}/infrastructure/api/auth/signup HTTP/1.1
content-type: application/json

{
  "name": "user1",
  "email": "user1@test.com",
  "password": "test"
}

### login a user
POST {{host}}/infrastructure/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "test",
  "password": "test"
}

### GET todo records
GET {{host}}/infrastructure/api/todos HTTP/1.1
content-type: application/json

### GET todo record by id
GET {{host}}/infrastructure/api/todos/2 HTTP/1.1
content-type: application/json

### CREATE todo record
POST {{host}}/infrastructure/api/todos HTTP/1.1
accept: text/plain
content-type: application/json

{
  "title": "todo 1"
}

### Update todo record
PATCH {{host}}/infrastructure/api/todos/2 HTTP/1.1
accept: text/plain
content-type: application/json

{
  "title": "todo1 updated",
  "completed": true
}

### DELETE todo record
DELETE  {{host}}/infrastructure/api/todos/18 HTTP/1.1
accept: text/plain
content-type: application/json
