services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app:delegated
      - sqlite_data:/app/prisma
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
    env_file:
      - .env.local

volumes:
  sqlite_data:
