services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - .:/app
      - sqlite_data:/app/prisma
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
    env_file:
      - .env.local

volumes:
  sqlite_data:
