version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - sqlite_data:/app/data
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env.local

volumes:
  sqlite_data:
