name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Todo-App-NextJS-CI:
    # runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [22.x]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format code
        run: yarn format:fix

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: yarn test

      - name: Build Storybook
        run: yarn storybook:build

      # - name: Test Storybook
      #   run: yarn test:storybook

      - name: Run Playwright tests
        run: npx playwright test

      # - name: Upload Playwright report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: playwright-report
      #     path: playwright-report

      - name: Build Next.js app
        run: yarn build
