name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    # runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [22.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: yarn test

      - name: Build Storybook
        run: yarn storybook:build
      
      - name: Run Playwright tests
        run: npx playwright test

      # - name: Upload Playwright report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: playwright-report
      #     path: playwright-report  