name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    # runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn test
      - run: yarn storybook:build
      - run: npx playwright install 
      - run: npx playwright test