name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
      - run: yarn storybook:build
      - run: npx playwright test